// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import model_1 from '/Users/lishuo/Desktop/lishuo/chat-electron/src/models/chat';
import model_2 from '/Users/lishuo/Desktop/lishuo/chat-electron/src/.umi/plugin-initialState/@@initialState';

export const models = {
model_1: { namespace: 'chat', model: model_1 },
model_2: { namespace: '@@initialState', model: model_2 },
} as const
