// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
// defineApp
export { defineApp } from './core/defineApp'
export type { RuntimeConfig } from './core/defineApp'
// plugins
export { Access, useAccess, useAccessMarkedRoutes } from '/Users/lishuo/Desktop/lishuo/chat-electron/src/.umi/plugin-access';
export { addLocale, setLocale, getLocale, getIntl, useIntl, injectIntl, formatMessage, FormattedMessage, getAllLocales, FormattedDate, FormattedDateParts, FormattedDisplayName, FormattedHTMLMessage, FormattedList, FormattedNumber, FormattedNumberParts, FormattedPlural, FormattedRelativeTime, FormattedTime, FormattedTimeParts, IntlProvider, RawIntlProvider, SelectLang } from '/Users/lishuo/Desktop/lishuo/chat-electron/src/.umi/plugin-locale';
export { Provider, useModel } from '/Users/lishuo/Desktop/lishuo/chat-electron/src/.umi/plugin-model';
export { useRequest, UseRequestProvider, request, getRequestInstance } from '/Users/lishuo/Desktop/lishuo/chat-electron/src/.umi/plugin-request';
// plugins types.d.ts
export * from '/Users/lishuo/Desktop/lishuo/chat-electron/src/.umi/plugin-access/types.d';
export * from '/Users/lishuo/Desktop/lishuo/chat-electron/src/.umi/plugin-antd/types.d';
export * from '/Users/lishuo/Desktop/lishuo/chat-electron/src/.umi/plugin-layout/types.d';
export * from '/Users/lishuo/Desktop/lishuo/chat-electron/src/.umi/plugin-request/types.d';
// @umijs/renderer-*
export { createBrowserHistory, createHashHistory, createMemoryHistory, Helmet, HelmetProvider, createSearchParams, generatePath, matchPath, matchRoutes, Navigate, NavLink, Outlet, resolvePath, useLocation, useMatch, useNavigate, useOutlet, useOutletContext, useParams, useResolvedPath, useRoutes, useSearchParams, useAppData, useClientLoaderData, useRouteProps, useSelectedRoutes, useServerLoaderData, renderClient, __getRoot, Link, useRouteData, __useFetcher, withRouter } from '/Users/lishuo/Desktop/lishuo/chat-electron/node_modules/.pnpm/@umijs+renderer-react@4.2.8_react-dom@18.1.0_react@18.1.0__react@18.1.0/node_modules/@umijs/renderer-react';
export type { History } from '/Users/lishuo/Desktop/lishuo/chat-electron/node_modules/.pnpm/@umijs+renderer-react@4.2.8_react-dom@18.1.0_react@18.1.0__react@18.1.0/node_modules/@umijs/renderer-react'
// umi/client/client/plugin
export { ApplyPluginsType, PluginManager } from '/Users/lishuo/Desktop/lishuo/chat-electron/node_modules/.pnpm/umi@4.2.8_@babel+core@7.24.6_@types+node@20.13.0_@types+react@18.3.3_eslint@8.35.0_jest@29.7._cpp6smmapi2kuvhz4wjvjt22ou/node_modules/umi/client/client/plugin.js';
export { history, createHistory } from './core/history';
export { terminal } from './core/terminal';
// react ssr
export const useServerInsertedHTML: Function = () => {};
// test
export { TestBrowser } from './testBrowser';
